import localFont from "next/font/local";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import BackToTopButton from "@/components/Buttont"; // Import the new component
import Footer from "@/components/Footer";
import Tel from "@/components/Tel";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "VapeHood",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" type="image/x-icon" width={250} height={250} />

        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <Tel />
        {children}
        <Footer />
        <BackToTopButton />
    
      </body>
    </html>
  );
}
